[package]
name = "himewm_layout_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
serde_json = "1.0.136"
fltk = "1.5.2"
fltk-theme = "0.7.4"
himewm_layout = { git = "https://github.com/artizanw/himewm" }
